# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab6/lab6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 200)
        MainWindow.setAccessibleName("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 221, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 100, 30))
        self.label.setObjectName("label")
        self.year_button = QtWidgets.QPushButton(self.groupBox)
        self.year_button.setGeometry(QtCore.QRect(110, 70, 100, 30))
        self.year_button.setObjectName("year_button")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 100, 30))
        self.label_2.setObjectName("label_2")
        self.year_input = QtWidgets.QLineEdit(self.groupBox)
        self.year_input.setGeometry(QtCore.QRect(110, 30, 100, 30))
        self.year_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.year_input.setObjectName("year_input")
        self.year_output = QtWidgets.QLineEdit(self.groupBox)
        self.year_output.setGeometry(QtCore.QRect(110, 110, 100, 30))
        self.year_output.setObjectName("year_output")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 371, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 250, 30))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.figure_button = QtWidgets.QPushButton(self.groupBox_2)
        self.figure_button.setGeometry(QtCore.QRect(260, 70, 100, 30))
        self.figure_button.setObjectName("figure_button")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 100, 30))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.figure_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.figure_input.setGeometry(QtCore.QRect(260, 30, 100, 30))
        self.figure_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.figure_input.setObjectName("figure_input")
        self.figure_output = QtWidgets.QLineEdit(self.groupBox_2)
        self.figure_output.setGeometry(QtCore.QRect(110, 110, 250, 30))
        self.figure_output.setObjectName("figure_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа 6"))
        self.groupBox.setTitle(_translate("MainWindow", "Китайский гороскоп"))
        self.label.setText(_translate("MainWindow", "Введите год"))
        self.year_button.setText(_translate("MainWindow", "Рассчитать"))
        self.label_2.setText(_translate("MainWindow", "Результат"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Угадайте фигуру"))
        self.label_3.setText(_translate("MainWindow", "Введите кол-во сторон у фигуры"))
        self.figure_button.setText(_translate("MainWindow", "Рассчитать"))
        self.label_4.setText(_translate("MainWindow", "Результат"))
